version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db